The "base_geometry" module
=========================

Using "base_geometry" function
_________________________

Bring in "BaseGeometry":
     >>> BaseGeometry = __import__("7-base_geometry").BaseGeometry

Create an instance of :
     >>> bg = BaseGeometry()

Test is bg an instance of BaseGeometry class
     >>> isinstance(bg, BaseGeometry)
     True

Test for normal use:
     >>> bg.integer_validator("age", 1)

Test for missing value argument
     >>> bg.integer_validator("name", )
     Traceback (most recent call last):
     ...
     TypeError: integer_validator() missing 1 required positional argument: 'value'

Test for negative numbers
     >>> bg.integer_validator("distance", -4)
     Traceback (most recent call last):
     ...
     ValueError: distance must be greater than 0

Test for zero value
     >>> bg.integer_validator("width", 0)
     Traceback (most recent call last):
     ...
     ValueError: width must be greater than 0

Test for integer validator if value is an int
     >>> bg.integer_validator("name", "John")
     Traceback (most recent call last):
     ...
     TypeError: name must be an integer

Test for integer validator if value is not none
     >>> bg.integer_validator("Red", None)
     Traceback (most recent call last):
     ...
     TypeError: Red must be an integer

Test for integer validator if no arguments are given
     >>> bg.integer_validator()
     Traceback (most recent call last):
     ...
     TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Test for integer validator if NaN
     >>> bg.integer_validator("nan", float("NaN"))
     Traceback (most recent call last):
     ...
     TypeError: nan must be an integer

Test for integer validator for tuple
     >>> bg.integer_validator("tuple", (1, 2, 3))
     Traceback (most recent call last):
     ...
     TypeError: tuple must be an integer

Test for integer validator for set
     >>> bg.integer_validator("set", {1, 2, 3})
     Traceback (most recent call last):
     ...
     TypeError: set must be an integer

Test for integer validator for dictionary
     >>> bg.integer_validator("dict", {"key": "value"})
     Traceback (most recent call last):
     ...
     TypeError: dict must be an integer

Test for area
     >>> bg.area()
     Traceback (most recent call last):
      ...
     Exception: area() is not implemented
